-- Seed data for ITSM

INSERT INTO organisations (name) VALUES
  ('Acme Corporation'),
  ('Blue Sky Technologies'),
  ('Harbour Legal Group');

INSERT INTO organisation_domains (organisation_id, domain) VALUES
  (1, 'acme.com'),
  (2, 'bluesky.io'),
  (3, 'harbourlegal.nz');

INSERT INTO contacts (first_name, last_name, email, organisation_id) VALUES
  ('Sarah',   'Mitchell',  'sarah.mitchell@acme.com',       1),
  ('James',   'Okafor',    'james.okafor@acme.com',         1),
  ('Priya',   'Sharma',    'priya.sharma@bluesky.io',       2),
  ('Tom',     'Nguyen',    'tom.nguyen@bluesky.io',         2),
  ('Rachel',  'Connelly',  'rachel.connelly@harbourlegal.nz', 3),
  ('Marcus',  'Webb',      'marcus.webb@harbourlegal.nz',   3);

-- Insert tickets (reference will be auto-generated by trigger)
INSERT INTO tickets (subject, description, status, priority, contact_id, created_at, updated_at) VALUES
  (
    'Cannot access VPN from home',
    'Since Monday I have been unable to connect to the company VPN from my home network. I get an authentication error even though my password is correct. I tried resetting my password but the problem persists.',
    'open', 'high', 1,
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '1 hour'
  ),
  (
    'Outlook keeps crashing on startup',
    'Outlook crashes immediately after the splash screen on my laptop. I have tried repairing the Office installation but it did not help. This started after the Windows update last week.',
    'in_progress', 'high', 2,
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '3 hours'
  ),
  (
    'Request for second monitor setup',
    'I would like to request a second monitor for my workstation. I do a lot of data analysis and having dual screens would significantly improve my workflow.',
    'open', 'low', 3,
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day'
  ),
  (
    'Shared drive permissions issue',
    'Several members of our team cannot access the Q2 Reports folder on the shared drive. We need read and write access restored urgently as we have a deadline tomorrow.',
    'in_progress', 'high', 4,
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '30 minutes'
  ),
  (
    'Printer on Level 3 not working',
    'The HP LaserJet on Level 3 is displaying a paper jam error but there is no paper in the tray. We have tried turning it off and on but it keeps showing the same error.',
    'on_hold', 'medium', 5,
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '2 days'
  ),
  (
    'New employee laptop setup required',
    'We have a new starter joining on Monday — Lena Park in the Marketing team. She will need a laptop configured with the standard software stack, email set up, and access to the shared drives.',
    'open', 'medium', 6,
    NOW() - INTERVAL '12 hours',
    NOW() - INTERVAL '12 hours'
  ),
  (
    'Password reset for document management system',
    'I have been locked out of the document management system after too many failed login attempts. Can you please reset my account?',
    'resolved', 'low', 1,
    NOW() - INTERVAL '10 days',
    NOW() - INTERVAL '9 days'
  ),
  (
    'Wi-Fi dropping in conference rooms A and B',
    'The wireless connection in the ground floor conference rooms drops every 20–30 minutes. This has been causing disruptions during client calls. The issue seems to have started after the network maintenance window.',
    'in_progress', 'medium', 3,
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '1 day'
  ),
  (
    'Software licence renewal — Adobe Creative Cloud',
    'Our Adobe Creative Cloud licences expire at the end of this month. Please can you arrange renewal for 4 seats: Sarah Mitchell, Tom Nguyen, Marcus Webb, and Rachel Connelly.',
    'on_hold', 'medium', 5,
    NOW() - INTERVAL '7 days',
    NOW() - INTERVAL '5 days'
  ),
  (
    'Keyboard and mouse not working after desk move',
    'After moving to my new desk yesterday, my wireless keyboard and mouse are no longer being recognised. The USB dongle is plugged in but no response from either device.',
    'resolved', 'low', 2,
    NOW() - INTERVAL '14 days',
    NOW() - INTERVAL '13 days'
  );

-- Replies for ticket 1 (Cannot access VPN)
INSERT INTO ticket_replies (ticket_id, body, is_agent_reply, created_at) VALUES
  (1, 'Hi Sarah, thanks for reaching out. I''ve looked into your account and can see the VPN authentication is failing at the MFA stage. Can you confirm which MFA app you are using and whether you recently changed your phone?', true, NOW() - INTERVAL '1 day 20 hours'),
  (1, 'Hi, I use Microsoft Authenticator. I did get a new phone about two weeks ago but I thought I transferred everything over properly.', false, NOW() - INTERVAL '1 day 18 hours'),
  (1, 'That explains it — MFA tokens don''t transfer automatically when you switch devices. I''ll send you a link to re-enrol your new phone. Once you''ve done that the VPN should work straight away.', true, NOW() - INTERVAL '1 day 17 hours');

-- Replies for ticket 2 (Outlook crashing)
INSERT INTO ticket_replies (ticket_id, body, is_agent_reply, created_at) VALUES
  (2, 'James, I''ve assigned this to myself. First step is to check whether the Windows update is conflicting with your Office version. Can you tell me your Office build number? You can find it in File > Account > About Outlook.', true, NOW() - INTERVAL '4 days 22 hours'),
  (2, 'The build number shown is 16.0.17628.20144', false, NOW() - INTERVAL '4 days 20 hours'),
  (2, 'Thanks. There is a known conflict with that build and the KB5039895 Windows update. I''m going to remote into your machine to roll back the update and apply the Office hotfix. Are you available in the next hour?', true, NOW() - INTERVAL '4 days 19 hours'),
  (2, 'Yes I''m at my desk now.', false, NOW() - INTERVAL '4 days 18 hours');

-- Replies for ticket 4 (Shared drive permissions)
INSERT INTO ticket_replies (ticket_id, body, is_agent_reply, created_at) VALUES
  (4, 'Hi Tom, I can see the Q2 Reports folder permissions were accidentally changed during a group policy update this morning. I''m restoring the correct access now — should be fixed within the next 10 minutes.', true, NOW() - INTERVAL '5 hours'),
  (4, 'Thank you so much, that is a relief. Please let me know once it''s done.', false, NOW() - INTERVAL '4 hours 45 minutes');

-- Replies for ticket 5 (Printer jam)
INSERT INTO ticket_replies (ticket_id, body, is_agent_reply, created_at) VALUES
  (5, 'Rachel, I''ve had a look at the printer remotely and the jam sensor appears to be faulty. We have ordered a replacement part which should arrive Thursday. In the meantime you can use the printer on Level 5.', true, NOW() - INTERVAL '2 days 18 hours'),
  (5, 'Understood, thanks for letting us know. We will use the Level 5 printer until it''s fixed.', false, NOW() - INTERVAL '2 days 16 hours');

-- Replies for ticket 7 (Resolved - DMS password reset)
INSERT INTO ticket_replies (ticket_id, body, is_agent_reply, created_at) VALUES
  (7, 'Sarah, I''ve reset your DMS account. You should receive a password reset email within the next few minutes. Please let me know if you don''t receive it.', true, NOW() - INTERVAL '9 days 22 hours'),
  (7, 'Got it, all sorted now. Thank you!', false, NOW() - INTERVAL '9 days 20 hours');

-- Replies for ticket 10 (Resolved - keyboard and mouse)
INSERT INTO ticket_replies (ticket_id, body, is_agent_reply, created_at) VALUES
  (10, 'James, wireless dongles sometimes need to be re-paired after being moved to a different USB port. Try pressing the connect button on the underside of both devices while the dongle is plugged in. Let me know if that doesn''t work and I''ll come to your desk.', true, NOW() - INTERVAL '13 days 22 hours'),
  (10, 'That did the trick! Both are working now. Thanks for the quick help.', false, NOW() - INTERVAL '13 days 20 hours');
